server:
  port: 8080


spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: sa
    driverClassName: org.h2.Driver
  h2:
    console:
      enable: true
  codec:
    max-in-memory-size: 2097152

  mvc:
    async:
      request-timeout: 3600000

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
#    generate-ddl: true
    hibernate:
      ddl-auto: none
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.H2Dialect

salary-server:
  url: http://localhost:8084

springdoc:
  swagger-ui:
#    path: /swagger-ui/api-docs.html
  model-converters:
    pageable-converter:
      enabled: true